version: "3"
services:
  postgres:
    image: "bitnami/postgresql"
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=izipark
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    networks:
      - app-net

  api:
    build:
      context: .
    container_name: izipark-api
    ports:
      - 3333:3333
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - "postgres"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
